### ISSUE TITLE
missing dependancies

### ISSUE THREAD

**Issue by syadnom** [ncareau/mikro-watch#10]
This file is missing:

PHP Warning:  require(/mikro-watch-master/vendor/autoload.php

I put a placeholder in there and then get:

PHP Fatal error:  Class 'Symfony\Component\Dotenv\Dotenv' not found

**Comment by syadnom** [comment]
fixed

**Comment by ncareau** [comment]
Can you tell me what you did to fix it ? maybe i should append my documentation to make it easier to use. Thanks !
